- hosts: kubernetes-{{ env }}-runner
  gather_facts: no
  vars:
    state: absent

  roles:
    - name: ec2_group
      tags:
        - destroy_security_groups
    - name: ec2_vpc
      tags:
        - destroy_vpc
