- name: determine the vpc ID
  ec2_vpc_net_facts:
    filters:
      tag:Name: "{{ vpc_name }}"
    region: "{{ region }}"
    profile: "{{ profile|default(omit) }}"
  register: vpc_facts

- name: ensure security groups are present
  ec2_group:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    rules: "{{ item.rules }}"
    vpc_id: "{{ vpc_facts.vpcs[0].id }}"
    tags: "{{ item.tags }}"
    region: "{{ region }}"
    profile: "{{ profile|default(omit) }}"
  with_items: "{{ security_groups }}"
