- hosts: kubernetes-compute:&{{ env }}:&runner
  gather_facts: no
  vars:
    state: absent

  roles:
    - name: ec2_asg
      tags:
        - destroy_asg

- hosts: kubernetes-fabric-{{ env }}-runner
  gather_facts: no
  vars:
    state: absent

  roles:
    - name: ec2_vpc_subnet
      tags:
        - destroy_subnets
    - name: ec2_group
      tags:
        - destroy_security_groups
    - name: ec2_vpc
      tags:
        - destroy_vpc
