security_groups:
- name: kubernetes-public-access-sg
  description: Allow external SSH, ICMP and HTTPS
  rules:
  - proto: tcp
    ports:
      - 22
      - 6443
    cidr_ip: 0.0.0.0/0
  - proto: icmp
    from_port: 8
    to_port: -1
    cidr_ip: 0.0.0.0/0
  tags:
    Environment: "{{ env }}"

- name: kubernetes-internal-access-sg
  description: Allow everything internally
  rules:
  - proto: all
    group_name: kubernetes-internal-access-sg
  tags:
    Environment: "{{ env }}"
